version: "3.9"

services:

  postgres:

    image: postgres:16

    container_name: blog_postgres

    restart: always

    ports:

      - "5432:5432"

    environment:

      POSTGRES_USER: postgres

      POSTGRES_PASSWORD: 123456

      POSTGRES_DB: blog_db

    volumes:

      - postgres_data:/var/lib/postgresql/data

volumes:

  postgres_data: